### ISSUE TITLE
cat: /dev/fd/63: No such file or directory

### ISSUE THREAD

**Issue by bereska** [neurobin/gencsr#3]
parustra@cf714 [~/letsacme]# ./gencsr
OpenSSL config file: /etc/pki/tls/openssl.cnf
Creating new key file: dom.key
Generating RSA private key, 4096 bit long modulus
...........................................................................................................................................++
.++
e is 65537 (0x10001)
Successfully created key file: dom.key
cat: /dev/fd/63: Нет такого файла или каталога
error on line -1 of /dev/fd/63
140718655518624:error:02001002:system library:fopen:No such file or directory:bss_file.c:169:fopen('/dev/fd/63','rb')
140718655518624:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:172:
140718655518624:error:0E078072:configuration file routines:DEF_LOAD:no such file:conf_def.c:197:
E: Failed to create CSR file!

**Comment by neurobin** [comment]
Fixed in new version
